apiversion: extensions/v1beta1
kind: Deployment
metadata:
  name: hostname-102-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostname
      appVersion: v102
  template:
    labels:
      app: hostname
      appVersion: v102
    containers:
      - name: nginx-hostname
        image: kubegoldenguide/nginx-hostname:1.0.2
        ports:
          - containerPort: 80
