apiVersion: v1
kind: Pod
metadata:
  - name: my-pvc-user-pod
spec:
  volumes:
    - name: a-persistent-volume
      persistentVolumeClaim:
        claimName: my-small-pvc
  containers:
    - name: my-pvc-container
      volumeMounts:
        - name: a-persistent-volume
          mountPath: /var/log
      image: alpine
      command: ['/bin/sh']
      args: ['-c', 'while true; do date >> /var/log/date.txt; sleep 5; done']
