apiVersion: v1
kind: Pod
metadata:
  name: liveness-readiness-pod
spec:
  containers:
    - name: server
      image: python:2.7-alpine
      readinessProbe:
        initialDelaySeconds: 30
        failureThreshold: 1
        httpGet:
          path: /
          port: 3000
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 4
        exec:
          command: ['ls', 'index.html']
      env:
        - name: DELAY_START
        value: '45'
      command: ['/bin/sh']
      args: ['-c', "echo 'Sleeping ...';  sleep $(DELAY_START); echo 'Starting server...'; python  -m SimpleHTTPServer"]
      
    
  
    
      
  
