apiVersion: v1
kind: Pod
metadata:
  name: pod-one
  namespace: red-team
spec:
  containers:
    - name: nginx-pod-one
      image: nginx-1.7.9
      resources:
        requests:
          cpu: 0.5
          memory: 768m
        limits:
          cpu: 2
          memory: 1024m
