apiVersion: v1
kind: Pod
metadata:
  name: hostname-pod-101
  labels:
    app: echo-hostname
    appVersion: v101
spec:
  containers:
    - name: nginx-hostname
      image: kubegoldenguide/nginx-hostname:1.0.1
      ports:
        - containerPort: 80

apiVersion: v1
kind: Pod
metadata:
  name: hostname-pod-102
  labels:
    app: echo-hostname
    appVersion: v102
spec:
  containers:
    - name: nginx-hostname
      image: kubegoldenguide/nginx-hostname:1.0.2
      ports:
        - containerPort: 80
